[run]
seed = 10
pars_space_boundaries = [
        [0.2, 0.4],
        [0.2, 0.4],
        [0.01, 0.09],
        [-0.2, -0.5],
    ]

number_of_particles = 1000
max_iterations = 200
min_iterations = 100
number_of_runs = 160
std_stop = 1e-8
exp_design =  "random"


[logging]
comments= "This is a comment\n I keep writing"

[model]






[run_for_compilation]
seed = 10
pars_space_boundaries = [
        [0.2, 0.4],
        [0.2, 0.4],
        [0.01, 0.09],
        [-0.2, -0.5],
    ]

number_of_particles = 50
max_iterations = 20
min_iterations = 20
number_of_runs = 20
std_stop = 1e-8
