[run]
seed = 10
pars_space_boundaries = [
        [0.01, 0.9],
        [0.01, 0.9],
        [0.001, 0.22],
        [-0.01, -0.9],
    ]

number_of_particles = 2000
max_iterations = 20000
min_iterations = 100
number_of_runs = 96
std_stop = 1e-8
exp_design =  "det"
true_parameters = [ 0.314216,  0.35833 ,  0.053851, -0.333695]



[logging]
comments= "This is a comment\n I keep writing"

[model]
number_of_qdots = 2
povm = "sic-povm"





[run_for_compilation]
seed = 10
pars_space_boundaries = [
        [0.2, 0.4],
        [0.2, 0.4],
        [0.01, 0.09],
        [-0.2, -0.5],
    ]

number_of_particles = 100
max_iterations = 5
min_iterations = 1
number_of_runs = 5
std_stop = 1e-8
